In [1]:
import numpy as np

In [2]:
n = np.arange(27)

In [3]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
type(n)

numpy.ndarray

In [5]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [6]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
m = np.asarray([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
type(m)

numpy.ndarray

In [10]:
np.delete(m,0)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.delete(m,8)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
import cv2